Sort Algorithms
JorgeAzarel/basic_c_programs pull request #1
Opened 2024-09-02 22:18 UTC by Murillo-DM

Implimentacion of the Sort Algorithms 

1. Bubble Sort
2. Merge Sort
3. Quick Sort
4. Selection Sort 
5. Insertion Sort

2024-09-02 22:31 UTC, Leraza commented on EjerciciosOrdenamiento/Bubble.c
Mueve las declaraciones de las funciones debajo de la funcion main, y genera los protipos arriba de la funcion main.

<prototipos de funcion>

2024-09-02 22:35 UTC, Leraza requested changes
Mueve los prototipos de las funciones arriba de la funcion main.
las declaraciones deben ir debajo de la funcion main

2024-09-02 22:39 UTC, Leraza commented on EjerciciosOrdenamiento/Insertion.c
> +void insertionSort(int array[], int n) {
¿por que en unos codigo usas el nombre de la funcion en inglés y en otros en español?

2024-09-02 22:53 UTC, Leraza commented on EjerciciosOrdenamiento/Insertion.c
> +void insertionSort(int array[], int n) {
Por favor usa CamelCase para TODO:

**Variables
Constantes
Funciones**

2024-09-02 23:04 UTC, Leraza commented on EjerciciosOrdenamiento/Bubble.c
> +/*#include <stdio.h>
¿Es necesario poner esos comentarios?

2024-09-02 23:04 UTC, Leraza reviewed
Por favor revisa los comentarios

2024-09-02 23:06 UTC, Murillo-DM commented on EjerciciosOrdenamiento/Bubble.c
> +/*#include <stdio.h>
No, no son necesarios, los eliminaré

2024-09-02 23:06 UTC, Leraza commented on EjerciciosOrdenamiento/Bubble.c
> +/*#include <stdio.h>
perfecto

2024-09-02 23:13 UTC, Leraza requested changes
Utiliza solo inglés para nombrar variables y funciones. 

![image](https://github.com/user-attachments/assets/0f3c9ca7-11b4-4235-977b-7912e80fc601)

2024-09-03 00:18 UTC, Leraza reviewed
Are you sure all this implementations work? 🤔

2024-09-03 00:41 UTC, Leraza approved these changes
Ok, it seems good.

According to Melissa the implementations test has been perfomed succesfully 

![image](https://github.com/user-attachments/assets/2671476b-7ae9-453e-abfb-994a480a58f4)

![image](https://github.com/user-attachments/assets/e87fe47c-ab82-4dfa-90e0-4b535f7ed413)

2024-09-03 00:43 UTC, merged

2024-09-03 00:47 UTC, Murillo-DM commented on EjerciciosOrdenamiento/Bubble.c
> +/*#include <stdio.h>
no